# Generated by Django 5.2.17 on 2026-09-05 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('tipo', models.CharField(choices=[('SENSOR', 'Sensor de Temperatura/Humedad'), ('COMEDERO', 'Comedero Automático'), ('EXTRACTOR', 'Extractor de Aire')], max_length=50, verbose_name='Tipo de Equipo')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento')], default='OPERATIVO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Granja')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('capacidad_total', models.PositiveIntegerField(verbose_name='Capacidad Total (Aves)')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Granja',
                'verbose_name_plural': 'Granjas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número/Código de Galpón')),
                ('tipo_galpon', models.CharField(choices=[('AUTOMATICO', 'Climatizado / Automático'), ('MANUAL', 'Convencional / Manual')], max_length=50, verbose_name='Tipo de Galpón')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad de Aves')),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galpones', to='granjas.granja', verbose_name='Granja')),
            ],
            options={
                'verbose_name': 'Galpón',
                'verbose_name_plural': 'Galpones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=30, unique=True, verbose_name='Código de Lote')),
                ('cantidad_inicial', models.PositiveIntegerField(verbose_name='Cantidad Inicial de Aves')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('estado', models.CharField(choices=[('CRECIMIENTO', 'En Crecimiento'), ('FINALIZADO', 'Procesado / Finalizado')], default='CRECIMIENTO', max_length=20, verbose_name='Estado')),
                ('galpon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='granjas.galpon', verbose_name='Galpón')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-id'],
            },
        ),
    ]
