# Generated by Django 5.2.17 on 2026-09-05 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social / Nombre')),
                ('ruc_dni', models.CharField(max_length=20, unique=True, verbose_name='RUC / DNI')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FormulaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formula', models.CharField(max_length=100, verbose_name='Nombre de la Fórmula')),
                ('etapa_nutricional', models.CharField(max_length=50, verbose_name='Etapa Nutricional')),
                ('porcentaje_proteina', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de Proteína (%)')),
            ],
            options={
                'verbose_name': 'Fórmula de Alimento',
                'verbose_name_plural': 'Fórmulas de Alimentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Insumo')),
                ('tipo_insumo', models.CharField(max_length=50, verbose_name='Tipo de Insumo')),
                ('unidad_medida', models.CharField(default='Kg', max_length=20, verbose_name='Unidad de Medida')),
                ('stock_minimo', models.PositiveIntegerField(default=100, verbose_name='Stock Mínimo')),
            ],
            options={
                'verbose_name': 'Materia Prima',
                'verbose_name_plural': 'Materias Primas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionHuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EXTRA', 'Extra'), ('GRANDE', 'Grande'), ('MEDIANO', 'Mediano'), ('ROTO', 'Roto / Mermas')], max_length=50, verbose_name='Categoría de Huevo')),
                ('fecha_cosecha', models.DateField(verbose_name='Fecha de Cosecha')),
                ('cantidad_jabas', models.PositiveIntegerField(verbose_name='Cantidad de Jabas')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Producción de Huevo',
                'verbose_name_plural': 'Producciones de Huevo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True, verbose_name='Placa del Vehículo')),
                ('conductor', models.CharField(max_length=100, verbose_name='Nombre del Conductor')),
                ('tipo_vehiculo', models.CharField(max_length=50, verbose_name='Tipo de Vehículo')),
                ('capacidad_carga_kg', models.PositiveIntegerField(verbose_name='Capacidad de Carga (Kg)')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VacunaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('principio_activo', models.CharField(max_length=100, verbose_name='Principio Activo')),
                ('via_administracion', models.CharField(max_length=50, verbose_name='Vía de Administración')),
                ('dosis_recomendada', models.CharField(max_length=50, verbose_name='Dosis Recomendada')),
            ],
            options={
                'verbose_name': 'Vacuna / Medicamento',
                'verbose_name_plural': 'Vacunas y Medicamentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('colegiatura', models.CharField(max_length=50, unique=True, verbose_name='Número de Colegiatura')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Veterinario',
                'verbose_name_plural': 'Veterinarios',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AlmacenAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_almacen', models.CharField(max_length=100, verbose_name='Nombre del Almacén / Silo')),
                ('capacidad_kilos', models.PositiveIntegerField(verbose_name='Capacidad Total (Kg)')),
                ('stock_disponible', models.PositiveIntegerField(verbose_name='Stock Disponible (Kg)')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='almacenes', to='granjas.formulaalimento', verbose_name='Fórmula Contenida')),
            ],
            options={
                'verbose_name': 'Almacén de Alimento',
                'verbose_name_plural': 'Almacenes de Alimento',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='formulaalimento',
            name='materia_prima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='granjas.materiaprima', verbose_name='Materia Prima Principal'),
        ),
        migrations.CreateModel(
            name='DetalleFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje (%)')),
                ('kilos_por_tonelada', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kg por Tonelada')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='granjas.formulaalimento', verbose_name='Fórmula')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granjas.materiaprima', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Detalle de Fórmula',
                'verbose_name_plural': 'Detalles de Fórmulas',
            },
        ),
        migrations.CreateModel(
            name='CompraMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de Compra')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Comprada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_materia_prima', to='granjas.proveedor', verbose_name='Proveedor')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granjas.materiaprima', verbose_name='Materia Prima')),
            ],
            options={
                'verbose_name': 'Compra de Materia Prima',
                'verbose_name_plural': 'Compras de Materias Primas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(max_length=50, unique=True, verbose_name='Número de Comprobante')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total ($)')),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=50, verbose_name='Estado de Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_venta', to='granjas.cliente', verbose_name='Cliente')),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='granjas.transporte', verbose_name='Unidad de Transporte')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Órdenes de Venta',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='granjas.lote', verbose_name='Lote de Aves')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='granjas.ordenventa', verbose_name='Orden de Venta')),
                ('produccion_huevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='granjas.produccionhuevo', verbose_name='Producción de Huevo')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
            },
        ),
        migrations.CreateModel(
            name='SuministroAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suministro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Suministro')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Suministrada (Kg)')),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suministros', to='granjas.almacenalimento', verbose_name='Almacén de Origen')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granjas.formulaalimento', verbose_name='Fórmula Suministrada')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suministros_alimento', to='granjas.lote', verbose_name='Lote Destino')),
            ],
            options={
                'verbose_name': 'Suministro de Alimento',
                'verbose_name_plural': 'Suministros de Alimentos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanVacunacionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50, verbose_name='Dosis Aplicada')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_aplicada', models.DateField(blank=True, null=True, verbose_name='Fecha de Aplicación')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_vacunacion', to='granjas.lote', verbose_name='Lote')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granjas.vacunamedicamento', verbose_name='Vacuna / Medicamento')),
                ('veterinario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='granjas.veterinario', verbose_name='Veterinario Responsable')),
            ],
            options={
                'verbose_name': 'Plan de Vacunación',
                'verbose_name_plural': 'Planes de Vacunación',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoEquipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('descripcion_trabajo', models.TextField(verbose_name='Descripción del Trabajo')),
                ('equipamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='granjas.equipamiento', verbose_name='Equipo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='granjas.veterinario', verbose_name='Técnico / Encargado')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Equipamiento',
                'verbose_name_plural': 'Mantenimientos de Equipamiento',
                'ordering': ['-id'],
            },
        ),
    ]
