# Generated by Django 5.2.17 on 2026-09-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjas', '0002_cliente_formulaalimento_materiaprima_produccionhuevo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('estado_contrato', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='granjas.granja', verbose_name='Granja')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granjas.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Contrato de Proveedor',
                'verbose_name_plural': 'Contratos de Proveedores',
            },
        ),
        migrations.AddField(
            model_name='granja',
            name='proveedores',
            field=models.ManyToManyField(related_name='granjas', through='granjas.ContratoProveedor', to='granjas.proveedor'),
        ),
        migrations.CreateModel(
            name='InspeccionSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateField(verbose_name='Fecha de Inspección')),
                ('resultado', models.CharField(max_length=50, verbose_name='Resultado (Aprobado/Observado)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='granjas.granja', verbose_name='Granja')),
            ],
            options={
                'verbose_name': 'Inspección Sanitaria',
                'verbose_name_plural': 'Inspecciones Sanitarias',
                'ordering': ['-fecha_inspeccion'],
            },
        ),
        migrations.CreateModel(
            name='LicenciaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_resolucion', models.CharField(max_length=50, unique=True, verbose_name='Código de Resolución SENASA')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('esta_vigente', models.BooleanField(default=True, verbose_name='¿Licencia Vigente?')),
                ('granja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licencia_sanitaria', to='granjas.granja', verbose_name='Granja')),
            ],
            options={
                'verbose_name': 'Licencia Sanitaria',
                'verbose_name_plural': 'Licencias Sanitarias',
            },
        ),
    ]
