# Generated by Django 5.2.17 on 2026-09-14 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjas', '0003_contratoproveedor_granja_proveedores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSanitarioLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_promedio_gr', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso Promedio (g)')),
                ('indice_mortalidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Índice de Mortalidad (%)')),
                ('conversion_alimenticia', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Índice de Conversión Alimenticia')),
                ('certificado_sanitario', models.BooleanField(default=False, verbose_name='¿Cuenta con Certificado Sanitario?')),
                ('fecha_evaluacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Evaluación')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_sanitario', to='granjas.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Perfil Sanitario de Lote',
                'verbose_name_plural': 'Perfiles Sanitarios de Lote',
            },
        ),
        migrations.CreateModel(
            name='VisitaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(verbose_name='Fecha de Visita')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('estado_lote', models.CharField(choices=[('SALUDABLE', 'Saludable'), ('OBSERVACION', 'En Observación'), ('CRITICO', 'Crítico')], default='SALUDABLE', max_length=20, verbose_name='Estado del Lote')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_veterinarias', to='granjas.lote', verbose_name='Lote')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_realizadas', to='granjas.veterinario', verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Visita Veterinaria',
                'verbose_name_plural': 'Visitas Veterinarias',
                'ordering': ['-fecha_visita'],
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='veterinarios',
            field=models.ManyToManyField(related_name='lotes_atendidos', through='granjas.VisitaVeterinaria', to='granjas.veterinario', verbose_name='Veterinarios que atendieron'),
        ),
    ]
