# Generated by Django 5.2.17
# LABORATORIO 07 - EJERCICIO 1: campos nuevos para transacciones y agregaciones

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjas', '0004_perfilsanitariolote_visitaveterinaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cupos_disponibles',
            field=models.PositiveIntegerField(default=10, verbose_name='Cupos Disponibles para Nuevos Contratos'),
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='cantidad_entregas_mensuales',
            field=models.PositiveIntegerField(default=4, verbose_name='Entregas Mensuales Pactadas'),
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='monto_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto Unitario por Entrega (S/)'),
        ),
    ]
