# Generated by Django 5.2.17 on 2026-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjas', '0005_proveedor_cupos_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccionhuevo',
            name='stock_jabas',
            field=models.PositiveIntegerField(default=50, verbose_name='Stock de Jabas Disponibles'),
        ),
        migrations.AlterField(
            model_name='produccionhuevo',
            name='cantidad_jabas',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Jabas Cosechadas'),
        ),
    ]
